import CausalLowerbound.PartB.CarrierFixedPoint
import CausalLowerbound.DiscreteLaw

/-! The fixed-point density is generated by one genuine countable label law. -/

noncomputable section
set_option autoImplicit false

namespace CausalLowerbound.PartB.CarrierCoefficients

variable {E V : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
  [NormedAddCommGroup V] {L : ℝ} (A : CarrierCoefficients E V L)

def labelLaw (K : ℝ) (hK : 0 ≤ K) (D : E) (hmass : A.mass K D ≤ 1) : DiscreteLaw ℕ :=
  DiscreteLaw.withRemainder (A.weight K D) (A.weight_summable K D)
    (A.weight_nonneg K hK D) hmass

def labeledAtom (e : E) (F : ℕ → E) : ℕ → E
  | 0 => e
  | m + 1 => F m

theorem atom_series_summable (K : ℝ) (hK : 0 ≤ K) (D e : E) (F : ℕ → E)
    (M : ℝ) (hF : ∀ m, ‖F m - e‖ ≤ M) :
    Summable (fun m => A.weight K D m • F m) := by
  apply summable_bounded_synthesis _ (A.weight_abs_summable K hK D) _ (M + ‖e‖)
  intro m
  calc
    _ ≤ ‖F m - e‖ + ‖e‖ := by simpa only [sub_add_cancel] using norm_add_le (F m - e) e
    _ ≤ _ := add_le_add_right (hF m) _

/-- Algebraic equality between the centered update and its convex-mixture form. -/
theorem update_eq_convex_series (K : ℝ) (hK : 0 ≤ K) (D e : E) (F : ℕ → E)
    (M : ℝ) (hF : ∀ m, ‖F m - e‖ ≤ M) :
    A.update K e F D = (1 - A.mass K D) • e + ∑' m, A.weight K D m • F m := by
  have hFsum := A.atom_series_summable K hK D e F M hF
  have hesum := (A.weight_summable K D).smul_const e
  unfold update
  simp only [smul_sub]
  rw [hFsum.tsum_sub hesum, (A.weight_summable K D).tsum_smul_const]
  simp only [mass, sub_smul, one_smul, sub_add_eq_add_sub, add_sub_assoc]

/-- This probability law's density moment is exactly the update, using an
absolutely convergent series rather than a formal identity of infinite sums. -/
theorem label_density_hasSum (K : ℝ) (hK : 0 ≤ K) (D e : E) (F : ℕ → E)
    (M : ℝ) (hF : ∀ m, ‖F m - e‖ ≤ M) (hmass : A.mass K D ≤ 1) :
    HasSum (fun n => (A.labelLaw K hK D hmass).weight n • labeledAtom e F n)
      (A.update K e F D) := by
  have htail := (A.atom_series_summable K hK D e F M hF).hasSum
  have h := (hasSum_nat_add_iff
    (f := fun n => (A.labelLaw K hK D hmass).weight n • labeledAtom e F n) 1).mp htail
  rw [A.update_eq_convex_series K hK D e F M hF]
  simpa only [Finset.sum_range_one, labelLaw, DiscreteLaw.withRemainder,
    labeledAtom, mass, add_comm] using h

theorem fixed_point_density_hasSum (K : ℝ) (hK : 0 ≤ K) (D e : E) (F : ℕ → E)
    (M : ℝ) (hF : ∀ m, ‖F m - e‖ ≤ M) (hmass : A.mass K D ≤ 1)
    (hfixed : A.update K e F D = D) :
    HasSum (fun n => (A.labelLaw K hK D hmass).weight n • labeledAtom e F n) D := by
  simpa only [hfixed] using A.label_density_hasSum K hK D e F M hF hmass

end CausalLowerbound.PartB.CarrierCoefficients
